before:
  hooks:
    - go mod download

builds:
  <- range .>
  - id: <.Name>
    main: cmd/<.Type>/<.Name>/main.go
    binary: <.Type>_<.Name>_{{ .Os }}_{{ .Arch }}

    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
  <- end >

archives:
  <range .>    
  - builds: [<.Name>]
    id: <.Name>
    files:
      - none*
    name_template: "{{ .Binary }}"
  <end>

snapshot:
  name_template: 'v{{ .Version }}'

release:
  # If set to true, will not auto-publish the release.
  draft: true
  prerelease: auto

  # Add extra pre-existing files to the release.
  # Prerequisites:
  # - build plugin binaries
  # - build plugin index.yaml
  extra_files:
    - glob: ./dist/*.tar.gz

changelog:
  skip: false
