# Resources you want to watch
resources:
  - name: pods
    namespaces:
      - all
      - default
      - prod
    events:
      - all
      - create
      - update
      - delete
  - name: services
    namespaces:
      - default
    events:
      - all
  - name: deployment
    namespaces:
      - default
    events:
      - all
  - name: ingresses
    namespaces:
      - default
    events:
      - all
# Events you want to watch
events:
  types:
    - normal
    - warning
  kinds:
    - name: pod
      namespaces:
        - default
    - name: service
      namespaces:
        - all
# RBAC events you want to watch
rbac:
  - name: roles
    namespaces:
      - all
    events:
      - all
  - name: rolebindings
    namespaces:
      - all
    events:
      - all
  - name: clusterroles
    namespaces:
      - all
    events:
      - all
  - name: clusterrolebindings
    namespace:
      - all
    events:
      - all
   
# Recommendations you want to receive
recommendations: true

# Channels configuration
communications:
  - slack:
      channel: 'xxxxx'
      token: 'xxxxxx'
  - email:
      smtpEmail: 'xxxxxx'
      smtpPassword: 'xxxxxxx'
      smtpServer: 'xxxxx'
      smtpPort: 'xxxxxx'
      notificationEmails:
        - user1@example.com
        - group1@example.com
