package main

import (
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/kubeshop/botkube/pkg/loggerx"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
	"gotest.tools/v3/golden"
)

// TestFetcher_preparePageList tests that we can prepare list of pages.
//
// To update golden files run:
// go test ./hack/assistant-setup/docs-fetcher/... -run=TestFetcher_preparePageList -update

func TestFetcher_preparePageList(t *testing.T) {
	// given
	fetcher := contentFetcher{
		log: loggerx.NewNoop(),
	}

	// when
	actual := fetcher.preparePageList(fixDocsPages(), fixMarketingPages())
	actualBytes, err := yaml.Marshal(actual)
	require.NoError(t, err)

	// then
	golden.Assert(t, string(actualBytes), filepath.Join(t.Name(), "prepare-page-list.golden.yaml"))
}

func TestFetcher_filePathForURL(t *testing.T) {
	// given
	prefix := "hack/assistant-setup/assets/"
	testCases := []struct {
		URL              string
		ExpectedFileName string
	}{
		{
			URL:              "https://docs.botkube.io/1.4/cli/commands/botkube_version",
			ExpectedFileName: "docs.botkube.io__1.4__cli__commands__botkube_version.md",
		},
		{
			URL:              "https://docs.botkube.io/license/",
			ExpectedFileName: "docs.botkube.io__license.md",
		},
		{
			URL:              "https://docs.botkube.io/architecture/cloud-teams",
			ExpectedFileName: "docs.botkube.io__architecture__cloud-teams.md",
		},
		{
			URL:              "https://docs.botkube.io/",
			ExpectedFileName: "docs.botkube.io.md",
		},
		{
			URL:              "https://botkube.io/",
			ExpectedFileName: "botkube.io.md",
		},
		{
			URL:              "https://botkube.io/blog/command-line-magic-simplify-your-life-with-custom-kubernetes-kubectrl-aliases-on-botkube",
			ExpectedFileName: "botkube.io__blog__command-line-magic-simplify-your-life-with-custom-kubernetes-kubectrl-aliases-on-botkube.md",
		},
	}

	for _, tc := range testCases {
		t.Run(tc.URL, func(t *testing.T) {
			fetcher := contentFetcher{
				log: loggerx.NewNoop(),
			}

			// when
			actual, err := fetcher.filePathForURL(tc.URL)

			// then
			require.NoError(t, err)
			assert.Equal(t, prefix+tc.ExpectedFileName, actual)
		})
	}
}

func fixDocsPages() []string {
	return []string{
		"https://docs.botkube.io/license/",
		"https://docs.botkube.io/search",
		"https://docs.botkube.io/support/",
		"https://docs.botkube.io/telemetry/",
		"https://docs.botkube.io/versions",
		"https://docs.botkube.io/1.4/",
		"https://docs.botkube.io/1.4/architecture/",
		"https://docs.botkube.io/1.4/cli/commands/botkube",
		"https://docs.botkube.io/1.4/cli/commands/botkube_config",
		"https://docs.botkube.io/1.4/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.4/cli/commands/botkube_install",
		"https://docs.botkube.io/1.4/cli/commands/botkube_login",
		"https://docs.botkube.io/1.4/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.4/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.4/cli/commands/botkube_version",
		"https://docs.botkube.io/1.4/cli/getting-started",
		"https://docs.botkube.io/1.4/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.4/configuration/",
		"https://docs.botkube.io/1.4/configuration/action",
		"https://docs.botkube.io/1.4/configuration/alias",
		"https://docs.botkube.io/1.4/configuration/communication/",
		"https://docs.botkube.io/1.4/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.4/configuration/executor/",
		"https://docs.botkube.io/1.4/configuration/executor/doctor",
		"https://docs.botkube.io/1.4/configuration/executor/exec",
		"https://docs.botkube.io/1.4/configuration/executor/flux",
		"https://docs.botkube.io/1.4/configuration/executor/helm",
		"https://docs.botkube.io/1.4/configuration/executor/kubectl",
		"https://docs.botkube.io/1.4/configuration/general",
		"https://docs.botkube.io/1.4/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.4/configuration/rbac",
		"https://docs.botkube.io/1.4/configuration/source/",
		"https://docs.botkube.io/1.4/configuration/source/argocd",
		"https://docs.botkube.io/1.4/configuration/source/github-events",
		"https://docs.botkube.io/1.4/configuration/source/keptn",
		"https://docs.botkube.io/1.4/configuration/source/kubernetes",
		"https://docs.botkube.io/1.4/configuration/source/prometheus",
		"https://docs.botkube.io/1.4/installation/discord/",
		"https://docs.botkube.io/1.4/installation/discord/cloud",
		"https://docs.botkube.io/1.4/installation/discord/self-hosted",
		"https://docs.botkube.io/1.4/installation/elasticsearch/",
		"https://docs.botkube.io/1.4/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.4/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.4/installation/mattermost/",
		"https://docs.botkube.io/1.4/installation/mattermost/cloud",
		"https://docs.botkube.io/1.4/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.4/installation/slack/",
		"https://docs.botkube.io/1.4/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.4/installation/slack/socket-slack/",
		"https://docs.botkube.io/1.4/installation/slack/socket-slack/self-hosted",
		"https://docs.botkube.io/1.4/installation/slack/socket-slack/socket-slack-cloud",
		"https://docs.botkube.io/1.4/installation/socketslack",
		"https://docs.botkube.io/1.4/installation/teams/",
		"https://docs.botkube.io/1.4/installation/webhook/",
		"https://docs.botkube.io/1.4/installation/webhook/cloud",
		"https://docs.botkube.io/1.4/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.4/operation/common-problems",
		"https://docs.botkube.io/1.4/operation/diagnostics",
		"https://docs.botkube.io/1.4/plugin/",
		"https://docs.botkube.io/1.4/plugin/custom-executor",
		"https://docs.botkube.io/1.4/plugin/custom-source",
		"https://docs.botkube.io/1.4/plugin/debugging",
		"https://docs.botkube.io/1.4/plugin/dependencies",
		"https://docs.botkube.io/1.4/plugin/interactive-messages",
		"https://docs.botkube.io/1.4/plugin/local-testing",
		"https://docs.botkube.io/1.4/plugin/quick-start",
		"https://docs.botkube.io/1.4/plugin/repo",
		"https://docs.botkube.io/1.4/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.4/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.4/usage/",
		"https://docs.botkube.io/1.4/usage/automated-actions",
		"https://docs.botkube.io/1.4/usage/event-notifications",
		"https://docs.botkube.io/1.4/usage/executor/",
		"https://docs.botkube.io/1.4/usage/executor/doctor",
		"https://docs.botkube.io/1.4/usage/executor/exec",
		"https://docs.botkube.io/1.4/usage/executor/flux",
		"https://docs.botkube.io/1.4/usage/executor/helm",
		"https://docs.botkube.io/1.4/usage/executor/kubectl",
		"https://docs.botkube.io/1.4/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.4/usage/source/",
		"https://docs.botkube.io/1.4/usage/source/argocd",
		"https://docs.botkube.io/1.4/usage/source/keptn",
		"https://docs.botkube.io/1.4/usage/source/kubernetes",
		"https://docs.botkube.io/1.4/usage/source/prometheus",
		"https://docs.botkube.io/1.5/",
		"https://docs.botkube.io/1.5/architecture/",
		"https://docs.botkube.io/1.5/cli/commands/botkube",
		"https://docs.botkube.io/1.5/cli/commands/botkube_config",
		"https://docs.botkube.io/1.5/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.5/cli/commands/botkube_install",
		"https://docs.botkube.io/1.5/cli/commands/botkube_login",
		"https://docs.botkube.io/1.5/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.5/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/1.5/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/1.5/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/1.5/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.5/cli/commands/botkube_version",
		"https://docs.botkube.io/1.5/cli/getting-started",
		"https://docs.botkube.io/1.5/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.5/configuration/",
		"https://docs.botkube.io/1.5/configuration/action",
		"https://docs.botkube.io/1.5/configuration/alias",
		"https://docs.botkube.io/1.5/configuration/communication/",
		"https://docs.botkube.io/1.5/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.5/configuration/executor/",
		"https://docs.botkube.io/1.5/configuration/executor/doctor",
		"https://docs.botkube.io/1.5/configuration/executor/exec",
		"https://docs.botkube.io/1.5/configuration/executor/flux",
		"https://docs.botkube.io/1.5/configuration/executor/helm",
		"https://docs.botkube.io/1.5/configuration/executor/kubectl",
		"https://docs.botkube.io/1.5/configuration/general",
		"https://docs.botkube.io/1.5/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.5/configuration/rbac",
		"https://docs.botkube.io/1.5/configuration/source/",
		"https://docs.botkube.io/1.5/configuration/source/argocd",
		"https://docs.botkube.io/1.5/configuration/source/github-events",
		"https://docs.botkube.io/1.5/configuration/source/keptn",
		"https://docs.botkube.io/1.5/configuration/source/kubernetes",
		"https://docs.botkube.io/1.5/configuration/source/prometheus",
		"https://docs.botkube.io/1.5/installation/discord/",
		"https://docs.botkube.io/1.5/installation/discord/cloud",
		"https://docs.botkube.io/1.5/installation/discord/self-hosted",
		"https://docs.botkube.io/1.5/installation/elasticsearch/",
		"https://docs.botkube.io/1.5/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.5/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.5/installation/mattermost/",
		"https://docs.botkube.io/1.5/installation/mattermost/cloud",
		"https://docs.botkube.io/1.5/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.5/installation/slack/",
		"https://docs.botkube.io/1.5/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.5/installation/slack/socket-slack",
		"https://docs.botkube.io/1.5/installation/socketslack",
		"https://docs.botkube.io/1.5/installation/teams/",
		"https://docs.botkube.io/1.5/installation/webhook/",
		"https://docs.botkube.io/1.5/installation/webhook/cloud",
		"https://docs.botkube.io/1.5/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.5/operation/common-problems",
		"https://docs.botkube.io/1.5/operation/diagnostics",
		"https://docs.botkube.io/1.5/plugin/",
		"https://docs.botkube.io/1.5/plugin/custom-executor",
		"https://docs.botkube.io/1.5/plugin/custom-source",
		"https://docs.botkube.io/1.5/plugin/debugging",
		"https://docs.botkube.io/1.5/plugin/dependencies",
		"https://docs.botkube.io/1.5/plugin/interactive-messages",
		"https://docs.botkube.io/1.5/plugin/local-testing",
		"https://docs.botkube.io/1.5/plugin/quick-start",
		"https://docs.botkube.io/1.5/plugin/repo",
		"https://docs.botkube.io/1.5/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.5/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.5/usage/",
		"https://docs.botkube.io/1.5/usage/automated-actions",
		"https://docs.botkube.io/1.5/usage/event-notifications",
		"https://docs.botkube.io/1.5/usage/executor/",
		"https://docs.botkube.io/1.5/usage/executor/doctor",
		"https://docs.botkube.io/1.5/usage/executor/exec",
		"https://docs.botkube.io/1.5/usage/executor/flux",
		"https://docs.botkube.io/1.5/usage/executor/helm",
		"https://docs.botkube.io/1.5/usage/executor/kubectl",
		"https://docs.botkube.io/1.5/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.5/usage/source/",
		"https://docs.botkube.io/1.5/usage/source/argocd",
		"https://docs.botkube.io/1.5/usage/source/keptn",
		"https://docs.botkube.io/1.5/usage/source/kubernetes",
		"https://docs.botkube.io/1.5/usage/source/prometheus",
		"https://docs.botkube.io/1.6/",
		"https://docs.botkube.io/1.6/architecture/",
		"https://docs.botkube.io/1.6/cli/commands/botkube",
		"https://docs.botkube.io/1.6/cli/commands/botkube_config",
		"https://docs.botkube.io/1.6/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.6/cli/commands/botkube_install",
		"https://docs.botkube.io/1.6/cli/commands/botkube_login",
		"https://docs.botkube.io/1.6/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.6/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/1.6/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/1.6/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/1.6/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.6/cli/commands/botkube_version",
		"https://docs.botkube.io/1.6/cli/getting-started",
		"https://docs.botkube.io/1.6/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.6/configuration/",
		"https://docs.botkube.io/1.6/configuration/action",
		"https://docs.botkube.io/1.6/configuration/alias",
		"https://docs.botkube.io/1.6/configuration/communication/",
		"https://docs.botkube.io/1.6/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.6/configuration/executor/",
		"https://docs.botkube.io/1.6/configuration/executor/doctor",
		"https://docs.botkube.io/1.6/configuration/executor/exec",
		"https://docs.botkube.io/1.6/configuration/executor/flux",
		"https://docs.botkube.io/1.6/configuration/executor/helm",
		"https://docs.botkube.io/1.6/configuration/executor/kubectl",
		"https://docs.botkube.io/1.6/configuration/general",
		"https://docs.botkube.io/1.6/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.6/configuration/rbac",
		"https://docs.botkube.io/1.6/configuration/source/",
		"https://docs.botkube.io/1.6/configuration/source/argocd",
		"https://docs.botkube.io/1.6/configuration/source/github-events",
		"https://docs.botkube.io/1.6/configuration/source/keptn",
		"https://docs.botkube.io/1.6/configuration/source/kubernetes",
		"https://docs.botkube.io/1.6/configuration/source/prometheus",
		"https://docs.botkube.io/1.6/installation/discord/",
		"https://docs.botkube.io/1.6/installation/discord/cloud",
		"https://docs.botkube.io/1.6/installation/discord/self-hosted",
		"https://docs.botkube.io/1.6/installation/elasticsearch/",
		"https://docs.botkube.io/1.6/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.6/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.6/installation/mattermost/",
		"https://docs.botkube.io/1.6/installation/mattermost/cloud",
		"https://docs.botkube.io/1.6/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.6/installation/slack/",
		"https://docs.botkube.io/1.6/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.6/installation/slack/socket-slack",
		"https://docs.botkube.io/1.6/installation/socketslack",
		"https://docs.botkube.io/1.6/installation/teams/",
		"https://docs.botkube.io/1.6/installation/webhook/",
		"https://docs.botkube.io/1.6/installation/webhook/cloud",
		"https://docs.botkube.io/1.6/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.6/operation/common-problems",
		"https://docs.botkube.io/1.6/operation/diagnostics",
		"https://docs.botkube.io/1.6/plugin/",
		"https://docs.botkube.io/1.6/plugin/custom-executor",
		"https://docs.botkube.io/1.6/plugin/custom-source",
		"https://docs.botkube.io/1.6/plugin/debugging",
		"https://docs.botkube.io/1.6/plugin/dependencies",
		"https://docs.botkube.io/1.6/plugin/interactive-messages",
		"https://docs.botkube.io/1.6/plugin/local-testing",
		"https://docs.botkube.io/1.6/plugin/quick-start",
		"https://docs.botkube.io/1.6/plugin/repo",
		"https://docs.botkube.io/1.6/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.6/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.6/usage/",
		"https://docs.botkube.io/1.6/usage/automated-actions",
		"https://docs.botkube.io/1.6/usage/event-notifications",
		"https://docs.botkube.io/1.6/usage/executor/",
		"https://docs.botkube.io/1.6/usage/executor/doctor",
		"https://docs.botkube.io/1.6/usage/executor/exec",
		"https://docs.botkube.io/1.6/usage/executor/flux",
		"https://docs.botkube.io/1.6/usage/executor/helm",
		"https://docs.botkube.io/1.6/usage/executor/kubectl",
		"https://docs.botkube.io/1.6/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.6/usage/source/",
		"https://docs.botkube.io/1.6/usage/source/argocd",
		"https://docs.botkube.io/1.6/usage/source/keptn",
		"https://docs.botkube.io/1.6/usage/source/kubernetes",
		"https://docs.botkube.io/1.6/usage/source/prometheus",
		"https://docs.botkube.io/1.7/",
		"https://docs.botkube.io/1.7/architecture/",
		"https://docs.botkube.io/1.7/cli/commands/botkube",
		"https://docs.botkube.io/1.7/cli/commands/botkube_config",
		"https://docs.botkube.io/1.7/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.7/cli/commands/botkube_install",
		"https://docs.botkube.io/1.7/cli/commands/botkube_login",
		"https://docs.botkube.io/1.7/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.7/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/1.7/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/1.7/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/1.7/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.7/cli/commands/botkube_version",
		"https://docs.botkube.io/1.7/cli/getting-started",
		"https://docs.botkube.io/1.7/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.7/configuration/",
		"https://docs.botkube.io/1.7/configuration/action",
		"https://docs.botkube.io/1.7/configuration/alias",
		"https://docs.botkube.io/1.7/configuration/communication/",
		"https://docs.botkube.io/1.7/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.7/configuration/executor/",
		"https://docs.botkube.io/1.7/configuration/executor/doctor",
		"https://docs.botkube.io/1.7/configuration/executor/exec",
		"https://docs.botkube.io/1.7/configuration/executor/flux",
		"https://docs.botkube.io/1.7/configuration/executor/helm",
		"https://docs.botkube.io/1.7/configuration/executor/kubectl",
		"https://docs.botkube.io/1.7/configuration/general",
		"https://docs.botkube.io/1.7/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.7/configuration/rbac",
		"https://docs.botkube.io/1.7/configuration/source/",
		"https://docs.botkube.io/1.7/configuration/source/argocd",
		"https://docs.botkube.io/1.7/configuration/source/github-events",
		"https://docs.botkube.io/1.7/configuration/source/keptn",
		"https://docs.botkube.io/1.7/configuration/source/kubernetes",
		"https://docs.botkube.io/1.7/configuration/source/prometheus",
		"https://docs.botkube.io/1.7/examples-and-tutorials/",
		"https://docs.botkube.io/1.7/examples-and-tutorials/getstarted/",
		"https://docs.botkube.io/1.7/examples-and-tutorials/integrations/",
		"https://docs.botkube.io/1.7/examples-and-tutorials/tutorials/",
		"https://docs.botkube.io/1.7/examples-and-tutorials/usecases/",
		"https://docs.botkube.io/1.7/examples-and-tutorials/videos/",
		"https://docs.botkube.io/1.7/installation/discord/",
		"https://docs.botkube.io/1.7/installation/discord/cloud",
		"https://docs.botkube.io/1.7/installation/discord/self-hosted",
		"https://docs.botkube.io/1.7/installation/elasticsearch/",
		"https://docs.botkube.io/1.7/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.7/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.7/installation/mattermost/",
		"https://docs.botkube.io/1.7/installation/mattermost/cloud",
		"https://docs.botkube.io/1.7/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.7/installation/slack/",
		"https://docs.botkube.io/1.7/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.7/installation/slack/socket-slack",
		"https://docs.botkube.io/1.7/installation/socketslack",
		"https://docs.botkube.io/1.7/installation/teams/",
		"https://docs.botkube.io/1.7/installation/webhook/",
		"https://docs.botkube.io/1.7/installation/webhook/cloud",
		"https://docs.botkube.io/1.7/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.7/operation/common-problems",
		"https://docs.botkube.io/1.7/operation/diagnostics",
		"https://docs.botkube.io/1.7/plugin/",
		"https://docs.botkube.io/1.7/plugin/custom-executor",
		"https://docs.botkube.io/1.7/plugin/custom-source",
		"https://docs.botkube.io/1.7/plugin/debugging",
		"https://docs.botkube.io/1.7/plugin/dependencies",
		"https://docs.botkube.io/1.7/plugin/interactive-messages",
		"https://docs.botkube.io/1.7/plugin/local-testing",
		"https://docs.botkube.io/1.7/plugin/quick-start",
		"https://docs.botkube.io/1.7/plugin/repo",
		"https://docs.botkube.io/1.7/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.7/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.7/usage/",
		"https://docs.botkube.io/1.7/usage/automated-actions",
		"https://docs.botkube.io/1.7/usage/event-notifications",
		"https://docs.botkube.io/1.7/usage/executor/",
		"https://docs.botkube.io/1.7/usage/executor/doctor",
		"https://docs.botkube.io/1.7/usage/executor/exec",
		"https://docs.botkube.io/1.7/usage/executor/flux",
		"https://docs.botkube.io/1.7/usage/executor/helm",
		"https://docs.botkube.io/1.7/usage/executor/kubectl",
		"https://docs.botkube.io/1.7/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.7/usage/source/",
		"https://docs.botkube.io/1.7/usage/source/argocd",
		"https://docs.botkube.io/1.7/usage/source/keptn",
		"https://docs.botkube.io/1.7/usage/source/kubernetes",
		"https://docs.botkube.io/1.7/usage/source/prometheus",
		"https://docs.botkube.io/1.8/",
		"https://docs.botkube.io/1.8/architecture/",
		"https://docs.botkube.io/1.8/cli/commands/botkube",
		"https://docs.botkube.io/1.8/cli/commands/botkube_config",
		"https://docs.botkube.io/1.8/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.8/cli/commands/botkube_install",
		"https://docs.botkube.io/1.8/cli/commands/botkube_login",
		"https://docs.botkube.io/1.8/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.8/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/1.8/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/1.8/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/1.8/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.8/cli/commands/botkube_version",
		"https://docs.botkube.io/1.8/cli/getting-started",
		"https://docs.botkube.io/1.8/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.8/configuration/",
		"https://docs.botkube.io/1.8/configuration/action",
		"https://docs.botkube.io/1.8/configuration/alias",
		"https://docs.botkube.io/1.8/configuration/communication/",
		"https://docs.botkube.io/1.8/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.8/configuration/executor/",
		"https://docs.botkube.io/1.8/configuration/executor/doctor",
		"https://docs.botkube.io/1.8/configuration/executor/exec",
		"https://docs.botkube.io/1.8/configuration/executor/flux",
		"https://docs.botkube.io/1.8/configuration/executor/helm",
		"https://docs.botkube.io/1.8/configuration/executor/kubectl",
		"https://docs.botkube.io/1.8/configuration/general",
		"https://docs.botkube.io/1.8/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.8/configuration/rbac",
		"https://docs.botkube.io/1.8/configuration/source/",
		"https://docs.botkube.io/1.8/configuration/source/argocd",
		"https://docs.botkube.io/1.8/configuration/source/github-events",
		"https://docs.botkube.io/1.8/configuration/source/keptn",
		"https://docs.botkube.io/1.8/configuration/source/kubernetes",
		"https://docs.botkube.io/1.8/configuration/source/prometheus",
		"https://docs.botkube.io/1.8/examples-and-tutorials/",
		"https://docs.botkube.io/1.8/examples-and-tutorials/getstarted/",
		"https://docs.botkube.io/1.8/examples-and-tutorials/integrations/",
		"https://docs.botkube.io/1.8/examples-and-tutorials/tutorials/",
		"https://docs.botkube.io/1.8/examples-and-tutorials/usecases/",
		"https://docs.botkube.io/1.8/examples-and-tutorials/videos/",
		"https://docs.botkube.io/1.8/installation/discord/",
		"https://docs.botkube.io/1.8/installation/discord/cloud",
		"https://docs.botkube.io/1.8/installation/discord/self-hosted",
		"https://docs.botkube.io/1.8/installation/elasticsearch/",
		"https://docs.botkube.io/1.8/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.8/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.8/installation/mattermost/",
		"https://docs.botkube.io/1.8/installation/mattermost/cloud",
		"https://docs.botkube.io/1.8/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.8/installation/slack/",
		"https://docs.botkube.io/1.8/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.8/installation/slack/socket-slack",
		"https://docs.botkube.io/1.8/installation/socketslack",
		"https://docs.botkube.io/1.8/installation/teams/",
		"https://docs.botkube.io/1.8/installation/webhook/",
		"https://docs.botkube.io/1.8/installation/webhook/cloud",
		"https://docs.botkube.io/1.8/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.8/operation/common-problems",
		"https://docs.botkube.io/1.8/operation/diagnostics",
		"https://docs.botkube.io/1.8/plugin/",
		"https://docs.botkube.io/1.8/plugin/custom-executor",
		"https://docs.botkube.io/1.8/plugin/custom-source",
		"https://docs.botkube.io/1.8/plugin/debugging",
		"https://docs.botkube.io/1.8/plugin/dependencies",
		"https://docs.botkube.io/1.8/plugin/interactive-messages",
		"https://docs.botkube.io/1.8/plugin/local-testing",
		"https://docs.botkube.io/1.8/plugin/quick-start",
		"https://docs.botkube.io/1.8/plugin/repo",
		"https://docs.botkube.io/1.8/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.8/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.8/usage/",
		"https://docs.botkube.io/1.8/usage/automated-actions",
		"https://docs.botkube.io/1.8/usage/event-notifications",
		"https://docs.botkube.io/1.8/usage/executor/",
		"https://docs.botkube.io/1.8/usage/executor/doctor",
		"https://docs.botkube.io/1.8/usage/executor/exec",
		"https://docs.botkube.io/1.8/usage/executor/flux",
		"https://docs.botkube.io/1.8/usage/executor/helm",
		"https://docs.botkube.io/1.8/usage/executor/kubectl",
		"https://docs.botkube.io/1.8/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.8/usage/source/",
		"https://docs.botkube.io/1.8/usage/source/argocd",
		"https://docs.botkube.io/1.8/usage/source/keptn",
		"https://docs.botkube.io/1.8/usage/source/kubernetes",
		"https://docs.botkube.io/1.8/usage/source/prometheus",
		"https://docs.botkube.io/1.9/",
		"https://docs.botkube.io/1.9/architecture/",
		"https://docs.botkube.io/1.9/architecture/cloud-teams",
		"https://docs.botkube.io/1.9/cli/commands/botkube",
		"https://docs.botkube.io/1.9/cli/commands/botkube_config",
		"https://docs.botkube.io/1.9/cli/commands/botkube_config_get",
		"https://docs.botkube.io/1.9/cli/commands/botkube_install",
		"https://docs.botkube.io/1.9/cli/commands/botkube_login",
		"https://docs.botkube.io/1.9/cli/commands/botkube_migrate",
		"https://docs.botkube.io/1.9/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/1.9/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/1.9/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/1.9/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/1.9/cli/commands/botkube_version",
		"https://docs.botkube.io/1.9/cli/getting-started",
		"https://docs.botkube.io/1.9/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/1.9/configuration/",
		"https://docs.botkube.io/1.9/configuration/action",
		"https://docs.botkube.io/1.9/configuration/alias",
		"https://docs.botkube.io/1.9/configuration/communication/",
		"https://docs.botkube.io/1.9/configuration/communication/vault-csi",
		"https://docs.botkube.io/1.9/configuration/executor/",
		"https://docs.botkube.io/1.9/configuration/executor/doctor",
		"https://docs.botkube.io/1.9/configuration/executor/exec",
		"https://docs.botkube.io/1.9/configuration/executor/flux",
		"https://docs.botkube.io/1.9/configuration/executor/helm",
		"https://docs.botkube.io/1.9/configuration/executor/kubectl",
		"https://docs.botkube.io/1.9/configuration/general",
		"https://docs.botkube.io/1.9/configuration/helm-chart-parameters",
		"https://docs.botkube.io/1.9/configuration/rbac",
		"https://docs.botkube.io/1.9/configuration/source/",
		"https://docs.botkube.io/1.9/configuration/source/argocd",
		"https://docs.botkube.io/1.9/configuration/source/github-events",
		"https://docs.botkube.io/1.9/configuration/source/keptn",
		"https://docs.botkube.io/1.9/configuration/source/kubernetes",
		"https://docs.botkube.io/1.9/configuration/source/prometheus",
		"https://docs.botkube.io/1.9/examples-and-tutorials/",
		"https://docs.botkube.io/1.9/examples-and-tutorials/getstarted/",
		"https://docs.botkube.io/1.9/examples-and-tutorials/integrations/",
		"https://docs.botkube.io/1.9/examples-and-tutorials/tutorials/",
		"https://docs.botkube.io/1.9/examples-and-tutorials/usecases/",
		"https://docs.botkube.io/1.9/examples-and-tutorials/videos/",
		"https://docs.botkube.io/1.9/installation/discord/",
		"https://docs.botkube.io/1.9/installation/discord/cloud",
		"https://docs.botkube.io/1.9/installation/discord/self-hosted",
		"https://docs.botkube.io/1.9/installation/elasticsearch/",
		"https://docs.botkube.io/1.9/installation/elasticsearch/cloud",
		"https://docs.botkube.io/1.9/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/1.9/installation/mattermost/",
		"https://docs.botkube.io/1.9/installation/mattermost/cloud",
		"https://docs.botkube.io/1.9/installation/mattermost/self-hosted",
		"https://docs.botkube.io/1.9/installation/slack/",
		"https://docs.botkube.io/1.9/installation/slack/cloud-slack",
		"https://docs.botkube.io/1.9/installation/slack/socket-slack",
		"https://docs.botkube.io/1.9/installation/socketslack",
		"https://docs.botkube.io/1.9/installation/teams/",
		"https://docs.botkube.io/1.9/installation/webhook/",
		"https://docs.botkube.io/1.9/installation/webhook/cloud",
		"https://docs.botkube.io/1.9/installation/webhook/self-hosted",
		"https://docs.botkube.io/1.9/operation/common-problems",
		"https://docs.botkube.io/1.9/operation/diagnostics",
		"https://docs.botkube.io/1.9/plugin/",
		"https://docs.botkube.io/1.9/plugin/custom-executor",
		"https://docs.botkube.io/1.9/plugin/custom-source",
		"https://docs.botkube.io/1.9/plugin/debugging",
		"https://docs.botkube.io/1.9/plugin/dependencies",
		"https://docs.botkube.io/1.9/plugin/interactive-messages",
		"https://docs.botkube.io/1.9/plugin/local-testing",
		"https://docs.botkube.io/1.9/plugin/quick-start",
		"https://docs.botkube.io/1.9/plugin/repo",
		"https://docs.botkube.io/1.9/plugin/troubleshooting.md",
		"https://docs.botkube.io/1.9/plugin/using-kubeconfig",
		"https://docs.botkube.io/1.9/usage/",
		"https://docs.botkube.io/1.9/usage/automated-actions",
		"https://docs.botkube.io/1.9/usage/event-notifications",
		"https://docs.botkube.io/1.9/usage/executor/",
		"https://docs.botkube.io/1.9/usage/executor/doctor",
		"https://docs.botkube.io/1.9/usage/executor/exec",
		"https://docs.botkube.io/1.9/usage/executor/flux",
		"https://docs.botkube.io/1.9/usage/executor/helm",
		"https://docs.botkube.io/1.9/usage/executor/kubectl",
		"https://docs.botkube.io/1.9/usage/interactive-output-filtering",
		"https://docs.botkube.io/1.9/usage/source/",
		"https://docs.botkube.io/1.9/usage/source/argocd",
		"https://docs.botkube.io/1.9/usage/source/keptn",
		"https://docs.botkube.io/1.9/usage/source/kubernetes",
		"https://docs.botkube.io/1.9/usage/source/prometheus",
		"https://docs.botkube.io/next/",
		"https://docs.botkube.io/next/architecture/",
		"https://docs.botkube.io/next/architecture/cloud-teams",
		"https://docs.botkube.io/next/cli/commands/botkube",
		"https://docs.botkube.io/next/cli/commands/botkube_config",
		"https://docs.botkube.io/next/cli/commands/botkube_config_get",
		"https://docs.botkube.io/next/cli/commands/botkube_install",
		"https://docs.botkube.io/next/cli/commands/botkube_login",
		"https://docs.botkube.io/next/cli/commands/botkube_migrate",
		"https://docs.botkube.io/next/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/next/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/next/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/next/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/next/cli/commands/botkube_version",
		"https://docs.botkube.io/next/cli/getting-started",
		"https://docs.botkube.io/next/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/next/configuration/",
		"https://docs.botkube.io/next/configuration/action",
		"https://docs.botkube.io/next/configuration/alias",
		"https://docs.botkube.io/next/configuration/communication/",
		"https://docs.botkube.io/next/configuration/communication/vault-csi",
		"https://docs.botkube.io/next/configuration/executor/",
		"https://docs.botkube.io/next/configuration/executor/doctor",
		"https://docs.botkube.io/next/configuration/executor/exec",
		"https://docs.botkube.io/next/configuration/executor/flux",
		"https://docs.botkube.io/next/configuration/executor/helm",
		"https://docs.botkube.io/next/configuration/executor/kubectl",
		"https://docs.botkube.io/next/configuration/general",
		"https://docs.botkube.io/next/configuration/helm-chart-parameters",
		"https://docs.botkube.io/next/configuration/rbac",
		"https://docs.botkube.io/next/configuration/source/",
		"https://docs.botkube.io/next/configuration/source/argocd",
		"https://docs.botkube.io/next/configuration/source/github-events",
		"https://docs.botkube.io/next/configuration/source/keptn",
		"https://docs.botkube.io/next/configuration/source/kubernetes",
		"https://docs.botkube.io/next/configuration/source/prometheus",
		"https://docs.botkube.io/next/examples-and-tutorials/",
		"https://docs.botkube.io/next/examples-and-tutorials/getstarted/",
		"https://docs.botkube.io/next/examples-and-tutorials/integrations/",
		"https://docs.botkube.io/next/examples-and-tutorials/tutorials/",
		"https://docs.botkube.io/next/examples-and-tutorials/usecases/",
		"https://docs.botkube.io/next/examples-and-tutorials/videos/",
		"https://docs.botkube.io/next/installation/discord/",
		"https://docs.botkube.io/next/installation/discord/cloud",
		"https://docs.botkube.io/next/installation/discord/self-hosted",
		"https://docs.botkube.io/next/installation/elasticsearch/",
		"https://docs.botkube.io/next/installation/elasticsearch/cloud",
		"https://docs.botkube.io/next/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/next/installation/mattermost/",
		"https://docs.botkube.io/next/installation/mattermost/cloud",
		"https://docs.botkube.io/next/installation/mattermost/self-hosted",
		"https://docs.botkube.io/next/installation/slack/",
		"https://docs.botkube.io/next/installation/slack/cloud-slack",
		"https://docs.botkube.io/next/installation/slack/socket-slack",
		"https://docs.botkube.io/next/installation/socketslack",
		"https://docs.botkube.io/next/installation/teams/",
		"https://docs.botkube.io/next/installation/webhook/",
		"https://docs.botkube.io/next/installation/webhook/cloud",
		"https://docs.botkube.io/next/installation/webhook/self-hosted",
		"https://docs.botkube.io/next/operation/common-problems",
		"https://docs.botkube.io/next/operation/diagnostics",
		"https://docs.botkube.io/next/plugin/",
		"https://docs.botkube.io/next/plugin/custom-executor",
		"https://docs.botkube.io/next/plugin/custom-source",
		"https://docs.botkube.io/next/plugin/debugging",
		"https://docs.botkube.io/next/plugin/dependencies",
		"https://docs.botkube.io/next/plugin/interactive-messages",
		"https://docs.botkube.io/next/plugin/local-testing",
		"https://docs.botkube.io/next/plugin/quick-start",
		"https://docs.botkube.io/next/plugin/repo",
		"https://docs.botkube.io/next/plugin/troubleshooting.md",
		"https://docs.botkube.io/next/plugin/using-kubeconfig",
		"https://docs.botkube.io/next/usage/",
		"https://docs.botkube.io/next/usage/automated-actions",
		"https://docs.botkube.io/next/usage/event-notifications",
		"https://docs.botkube.io/next/usage/executor/",
		"https://docs.botkube.io/next/usage/executor/doctor",
		"https://docs.botkube.io/next/usage/executor/exec",
		"https://docs.botkube.io/next/usage/executor/flux",
		"https://docs.botkube.io/next/usage/executor/helm",
		"https://docs.botkube.io/next/usage/executor/kubectl",
		"https://docs.botkube.io/next/usage/interactive-output-filtering",
		"https://docs.botkube.io/next/usage/source/",
		"https://docs.botkube.io/next/usage/source/argocd",
		"https://docs.botkube.io/next/usage/source/keptn",
		"https://docs.botkube.io/next/usage/source/kubernetes",
		"https://docs.botkube.io/next/usage/source/prometheus",
		"https://docs.botkube.io/community/contribute/",
		"https://docs.botkube.io/community/contribute/elasticsearch-develop",
		"https://docs.botkube.io/community/contribute/ms-teams-develop",
		"https://docs.botkube.io/community/contribute/release",
		"https://docs.botkube.io/community/contribute/webhook-develop",
		"https://docs.botkube.io/community/credits",
		"https://docs.botkube.io/",
		"https://docs.botkube.io/architecture/",
		"https://docs.botkube.io/architecture/cloud-teams",
		"https://docs.botkube.io/cli/commands/botkube",
		"https://docs.botkube.io/cli/commands/botkube_config",
		"https://docs.botkube.io/cli/commands/botkube_config_get",
		"https://docs.botkube.io/cli/commands/botkube_install",
		"https://docs.botkube.io/cli/commands/botkube_login",
		"https://docs.botkube.io/cli/commands/botkube_migrate",
		"https://docs.botkube.io/cli/commands/botkube_telemetry",
		"https://docs.botkube.io/cli/commands/botkube_telemetry_disable",
		"https://docs.botkube.io/cli/commands/botkube_telemetry_enable",
		"https://docs.botkube.io/cli/commands/botkube_uninstall",
		"https://docs.botkube.io/cli/commands/botkube_version",
		"https://docs.botkube.io/cli/getting-started",
		"https://docs.botkube.io/cli/migrating-installation-to-botkube-cloud",
		"https://docs.botkube.io/configuration/",
		"https://docs.botkube.io/configuration/action",
		"https://docs.botkube.io/configuration/alias",
		"https://docs.botkube.io/configuration/communication/",
		"https://docs.botkube.io/configuration/communication/vault-csi",
		"https://docs.botkube.io/configuration/executor/",
		"https://docs.botkube.io/configuration/executor/doctor",
		"https://docs.botkube.io/configuration/executor/exec",
		"https://docs.botkube.io/configuration/executor/flux",
		"https://docs.botkube.io/configuration/executor/helm",
		"https://docs.botkube.io/configuration/executor/kubectl",
		"https://docs.botkube.io/configuration/general",
		"https://docs.botkube.io/configuration/helm-chart-parameters",
		"https://docs.botkube.io/configuration/rbac",
		"https://docs.botkube.io/configuration/source/",
		"https://docs.botkube.io/configuration/source/argocd",
		"https://docs.botkube.io/configuration/source/github-events",
		"https://docs.botkube.io/configuration/source/keptn",
		"https://docs.botkube.io/configuration/source/kubernetes",
		"https://docs.botkube.io/configuration/source/prometheus",
		"https://docs.botkube.io/examples-and-tutorials/",
		"https://docs.botkube.io/examples-and-tutorials/getstarted/",
		"https://docs.botkube.io/examples-and-tutorials/integrations/",
		"https://docs.botkube.io/examples-and-tutorials/tutorials/",
		"https://docs.botkube.io/examples-and-tutorials/usecases/",
		"https://docs.botkube.io/examples-and-tutorials/videos/",
		"https://docs.botkube.io/installation/discord/",
		"https://docs.botkube.io/installation/discord/cloud",
		"https://docs.botkube.io/installation/discord/self-hosted",
		"https://docs.botkube.io/installation/elasticsearch/",
		"https://docs.botkube.io/installation/elasticsearch/cloud",
		"https://docs.botkube.io/installation/elasticsearch/self-hosted",
		"https://docs.botkube.io/installation/mattermost/",
		"https://docs.botkube.io/installation/mattermost/cloud",
		"https://docs.botkube.io/installation/mattermost/self-hosted",
		"https://docs.botkube.io/installation/slack/",
		"https://docs.botkube.io/installation/slack/cloud-slack",
		"https://docs.botkube.io/installation/slack/socket-slack",
		"https://docs.botkube.io/installation/socketslack",
		"https://docs.botkube.io/installation/teams/",
		"https://docs.botkube.io/installation/webhook/",
		"https://docs.botkube.io/installation/webhook/cloud",
		"https://docs.botkube.io/installation/webhook/self-hosted",
		"https://docs.botkube.io/operation/common-problems",
		"https://docs.botkube.io/operation/diagnostics",
		"https://docs.botkube.io/plugin/",
		"https://docs.botkube.io/plugin/custom-executor",
		"https://docs.botkube.io/plugin/custom-source",
		"https://docs.botkube.io/plugin/debugging",
		"https://docs.botkube.io/plugin/dependencies",
		"https://docs.botkube.io/plugin/interactive-messages",
		"https://docs.botkube.io/plugin/local-testing",
		"https://docs.botkube.io/plugin/quick-start",
		"https://docs.botkube.io/plugin/repo",
		"https://docs.botkube.io/plugin/troubleshooting.md",
		"https://docs.botkube.io/plugin/using-kubeconfig",
		"https://docs.botkube.io/usage/",
		"https://docs.botkube.io/usage/automated-actions",
		"https://docs.botkube.io/usage/event-notifications",
		"https://docs.botkube.io/usage/executor/",
		"https://docs.botkube.io/usage/executor/doctor",
		"https://docs.botkube.io/usage/executor/exec",
		"https://docs.botkube.io/usage/executor/flux",
		"https://docs.botkube.io/usage/executor/helm",
		"https://docs.botkube.io/usage/executor/kubectl",
		"https://docs.botkube.io/usage/interactive-output-filtering",
		"https://docs.botkube.io/usage/source/",
		"https://docs.botkube.io/usage/source/argocd",
		"https://docs.botkube.io/usage/source/keptn",
		"https://docs.botkube.io/usage/source/kubernetes",
		"https://docs.botkube.io/usage/source/prometheus",
	}
}

func fixMarketingPages() []string {
	return []string{
		"\n            https://botkube.io\n        ",
		"\n            https://botkube.io/professional-services-partner\n        ",
		"\n            https://botkube.io/support\n        ",
		"\n            https://botkube.io/integrations\n        ",
		"\n            https://botkube.io/pricing\n        ",
		"\n            https://botkube.io/contact\n        ",
		"\n            https://botkube.io/learn\n        ",
		"\n            https://botkube.io/privacy-policy\n        ",
		"\n            https://botkube.io/terms-and-conditions\n        ",
		"\n            https://botkube.io/events\n        ",
		"\n            https://botkube.io/features\n        ",
		"\n            https://botkube.io/news\n        ",
		"\n            https://botkube.io/blog\n        ",
		"\n            https://botkube.io/slack-app\n        ",
		"\n            https://botkube.io/case-studies\n        ",
		"\n            https://botkube.io/solutions/enabling-developers\n        ",
		"\n            https://botkube.io/about\n        ",
		"\n            https://botkube.io/blog/ai-for-kubernetes-operations\n        ",
		"\n            https://botkube.io/blog/argo-cd-botkube-integration\n        ",
		"\n            https://botkube.io/blog/beginners-guide-to-botkube-plugin-development-how-botkube-plug-ins-can-unify-your-cloud-native-tools\n        ",
		"\n            https://botkube.io/blog/best-practices-for-kubernetes-troubleshooting-in-multi-cluster-environments\n        ",
		"\n            https://botkube.io/blog/botkube-1-6-release\n        ",
		"\n            https://botkube.io/blog/botkube-5-essential-devopstasks-to-automate\n        ",
		"\n            https://botkube.io/blog/botkube-open-source-to-cloud-migration\n        ",
		"\n            https://botkube.io/blog/botkube-socket-slack-getting-started\n        ",
		"\n            https://botkube.io/blog/botkube-takes-on-amsterdam-a-kubecon-recap\n        ",
		"\n            https://botkube.io/blog/botkube-v0-18-0-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v013-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v014-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v015-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v016-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v017-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v1-1-0-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v1-2-0-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v1-3-0-release-notes\n        ",
		"\n            https://botkube.io/blog/botkube-v1-4-0-release-notes\n        ",
		"\n            https://botkube.io/blog/build-a-github-issues-reporter-for-failing-kubernetes-apps-with-botkube-plugins\n        ",
		"\n            https://botkube.io/blog/building-a-chatgpt-plugin-from-ideation-to-implementation\n        ",
		"\n            https://botkube.io/blog/command-line-magic-simplify-your-life-with-custom-kubernetes-kubectrl-aliases-on-botkube\n        ",
		"\n            https://botkube.io/blog/configure-event-sources-with-new-botkube-filters\n        ",
		"\n            https://botkube.io/blog/creating-the-botkube-flux-plugin-for-day-2-operations\n        ",
		"\n            https://botkube.io/blog/doctor-plug-in-tutorial\n        ",
		"\n            https://botkube.io/blog/empowering-your-kubernetes-multi-cluster-observability-with-intelligent-monitoring\n        ",
		"\n            https://botkube.io/blog/enhancing-gitops-workflows-with-botkube\n        ",
		"\n            https://botkube.io/blog/explore-the-new-era-of-aiops-with-botkubes-ai-assistant\n        ",
		"\n            https://botkube.io/blog/five-essential-kubernetes-tasks\n        ",
		"\n            https://botkube.io/blog/get-botkube-running-in-under-3-minutes-the-new-slack-app\n        ",
		"\n            https://botkube.io/blog/getting-started-with-botkube-and-argocd\n        ",
		"\n            https://botkube.io/blog/implementing-your-own-botkube-plugin-a-real-life-use-case\n        ",
		"\n            https://botkube.io/blog/integrating-microsoft-teams-with-azure-for-kubernetes-deployments\n        ",
		"\n            https://botkube.io/blog/introducing-botkube-v1-0-the-future-of-kubernetes-troubleshooting\n        ",
		"\n            https://botkube.io/blog/introducing-botkubes-integration-with-flux\n        ",
		"\n            https://botkube.io/blog/is-chatops-a-kubernetes-dashboard-alternative\n        ",
		"\n            https://botkube.io/blog/level-up-your-sre-workflow-automating-manual-tasks-with-botkube-ai-assistant\n        ",
		"\n            https://botkube.io/blog/leveraging-botkube-for-kubernetes-cost-optimization-and-reporting\n        ",
		"\n            https://botkube.io/blog/maximize-your-devops-teams-efficiency-with-botkube-and-microsoft-teams\n        ",
		"\n            https://botkube.io/blog/microsoft-teams-integration-for-botkube-a-technical-journey\n        ",
		"\n            https://botkube.io/blog/optimizing-collaboration-and-notifications-with-the-botkube-argocd-plugin\n        ",
		"\n            https://botkube.io/blog/real-time-platform-engineer-advice-ai-assistant\n        ",
		"\n            https://botkube.io/blog/revolutionize-your-kubernetes-troubleshooting-workflow-with-microsoft-teams-and-botkube\n        ",
		"\n            https://botkube.io/blog/scaling-new-heights-taking-botkube-to-scale-20x\n        ",
		"\n            https://botkube.io/blog/simplify-kubernetes-with-botkubes-ai-developer-self-service-made-easy\n        ",
		"\n            https://botkube.io/blog/step-by-step-tutorial-leveraging-botkubes-cloud-slack-feature-for-kubernetes-collaborative-troubleshooting\n        ",
		"\n            https://botkube.io/blog/streamlining-gitops-with-the-botkube-flux-plugin\n        ",
		"\n            https://botkube.io/blog/streamlining-kubernetes-management-a-closer-look-at-botkube-chatops\n        ",
		"\n            https://botkube.io/blog/supercharging-developer-collaboration-how-chatops-lives-on-with-botkube\n        ",
		"\n            https://botkube.io/blog/the-state-of-kubernetes-errors-in-2023\n        ",
		"\n            https://botkube.io/blog/use-chatgpt-to-troubleshoot-kubernetes-errors-with-botkubes-doctor\n        ",
		"\n            https://botkube.io/tags/ai\n        ",
		"\n            https://botkube.io/tags/aiops\n        ",
		"\n            https://botkube.io/tags/argo-cd\n        ",
		"\n            https://botkube.io/tags/botkube-cloud\n        ",
		"\n            https://botkube.io/tags/chatops\n        ",
		"\n            https://botkube.io/tags/development\n        ",
		"\n            https://botkube.io/tags/gitops\n        ",
		"\n            https://botkube.io/tags/helm\n        ",
		"\n            https://botkube.io/tags/kubecon\n        ",
		"\n            https://botkube.io/tags/kubernetes\n        ",
		"\n            https://botkube.io/tags/microsoft-teams\n        ",
		"\n            https://botkube.io/tags/monitoring\n        ",
		"\n            https://botkube.io/tags/newsletter\n        ",
		"\n            https://botkube.io/tags/release\n        ",
		"\n            https://botkube.io/tags/slack\n        ",
		"\n            https://botkube.io/tags/tutorial\n        ",
		"\n            https://botkube.io/integration/argo-cd-botkube-kubernetes-integration\n        ",
		"\n            https://botkube.io/integration/botkube-flux-kubernetes-integration\n        ",
		"\n            https://botkube.io/integration/chatgpt-botkube-kubernetes-integration\n        ",
		"\n            https://botkube.io/integration/custom-executor-plugin\n        ",
		"\n            https://botkube.io/integration/discord\n        ",
		"\n            https://botkube.io/integration/helm\n        ",
		"\n            https://botkube.io/integration/kasten\n        ",
		"\n            https://botkube.io/integration/keptn\n        ",
		"\n            https://botkube.io/integration/mattermost\n        ",
		"\n            https://botkube.io/integration/prometheus\n        ",
		"\n            https://botkube.io/integration/slack\n        ",
		"\n            https://botkube.io/integration/teams\n        ",
		"\n            https://botkube.io/learn/ai-for-devops\n        ",
		"\n            https://botkube.io/learn/ai-tools-for-kubernetes\n        ",
		"\n            https://botkube.io/learn/aiops-tools\n        ",
		"\n            https://botkube.io/learn/automate-kubernetes-compliance-with-botkube\n        ",
		"\n            https://botkube.io/learn/azure-kubernetes-services\n        ",
		"\n            https://botkube.io/learn/best-gitops-tools-for-kubernetes\n        ",
		"\n            https://botkube.io/learn/chatops\n        ",
		"\n            https://botkube.io/learn/cluster-status-check\n        ",
		"\n            https://botkube.io/learn/copying-files-with-kubectl-cp\n        ",
		"\n            https://botkube.io/learn/createcontainererror\n        ",
		"\n            https://botkube.io/learn/demystifying-kubectl-drain-safely-evacuating-kubernetes-nodes\n        ",
		"\n            https://botkube.io/learn/exit-code-125-issues\n        ",
		"\n            https://botkube.io/learn/failed-to-push-some-refs-to\n        ",
		"\n            https://botkube.io/learn/fix-the-unable-to-get-local-issuer-certificate-error-in-kubernetes\n        ",
		"\n            https://botkube.io/learn/helm-charts\n        ",
		"\n            https://botkube.io/learn/how-botkube-makes-monitoring-kubernetes-easy\n        ",
		"\n            https://botkube.io/learn/how-to-debug-crashloopbackoff\n        ",
		"\n            https://botkube.io/learn/how-to-fix-fatal-remote-origin-already-exists-git-error\n        ",
		"\n            https://botkube.io/learn/is-kubernetes-an-operating-system\n        ",
		"\n            https://botkube.io/learn/kubectl-cheat-sheet\n        ",
		"\n            https://botkube.io/learn/kubernetes-alerts-to-teams\n        ",
		"\n            https://botkube.io/learn/kubernetes-audit-log-best-practices\n        ",
		"\n            https://botkube.io/learn/kubernetes-errors\n        ",
		"\n            https://botkube.io/learn/kubernetes-monitoring-tools\n        ",
		"\n            https://botkube.io/learn/kubernetes-observability-best-practices\n        ",
		"\n            https://botkube.io/learn/kubernetes-rollbacks-a-guide\n        ",
		"\n            https://botkube.io/learn/making-slack-talk-kubernetes-slack-powered-chatops-for-k8s\n        ",
		"\n            https://botkube.io/learn/managing-kubernetes-clusters-from-chat\n        ",
		"\n            https://botkube.io/learn/platform-engineering\n        ",
		"\n            https://botkube.io/learn/real-time-event-log-in-slack\n        ",
		"\n            https://botkube.io/learn/roles-of-swes-and-sres\n        ",
		"\n            https://botkube.io/learn/slackops\n        ",
		"\n            https://botkube.io/learn/spring-boot\n        ",
		"\n            https://botkube.io/learn/the-benefits-and-use-cases-of-using-botkube-in-kubernetes-clusters\n        ",
		"\n            https://botkube.io/learn/turning-kubernetes-k8s-alerts-into-k8s-notifications\n        ",
		"\n            https://botkube.io/learn/understanding-kubernetes-executors\n        ",
		"\n            https://botkube.io/learn/understanding-yaml-commenting\n        ",
		"\n            https://botkube.io/learn/use-cases-for-aiops-platform\n        ",
		"\n            https://botkube.io/learn/what-is-oomkilled\n        ",
		"\n            https://botkube.io/learn-main-topic/ai\n        ",
		"\n            https://botkube.io/learn-main-topic/definitions\n        ",
		"\n            https://botkube.io/learn-main-topic/errors\n        ",
		"\n            https://botkube.io/learn-main-topic/monitoring-kubernetes\n        ",
		"\n            https://botkube.io/learn-main-topic/use-cases\n        ",
		"\n            https://botkube.io/lp/5-essential-kubernetes-monitoring-and-troubleshooting-tasks-to-automate\n        ",
		"\n            https://botkube.io/lp/mastering-developer-self-service\n        ",
		"\n            https://botkube.io/lp/zapier-for-kubernetes\n        ",
		"\n            https://botkube.io/case-studies/civo\n        ",
	}
}
