name: Tag build

on:
  push:
    tags:
      - '*'

env:
  BUCKET_NAME: botkube-cloud-plugins
  VERSION: "${{ github.ref_name }}"

jobs:
  release:
    name: Release plugins
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.CLOUD_PLUGINS_BUCKET_CREDS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
          version: latest

      - name: Build plugins and generate plugins index.yaml
        env:
          PLUGIN_DOWNLOAD_URL_BASE_PATH: "${{ env.VERSION }}"
        run: |
          make build-plugins-archives
          USE_ARCHIVE=true make gen-plugin-index

      - name: Upload plugins to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'dist'
          destination: '${{ env.BUCKET_NAME }}/${{ env.VERSION }}'
          glob: '*.tar.gz'
          parent: false

      - name: Upload plugin index to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: 'plugins-index.yaml'
          destination: '${{ env.BUCKET_NAME }}/${{ env.VERSION }}'
